apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: Deployment
    name: web-nodejs
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value:            "registry-quay-quay-operator.apps.cluster-424xp.424xp.sandbox1774.opentlc.com/workshop49/globex-ui:main-b183894cabd3eebaa5844143d5ac60dc9863fb57"
